[package]
name = "storage-fsm-macro"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.8.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.102", features = ["full"] }

[lib]
proc-macro = true
